package UserInterface;

import java.awt.Component;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTree;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author Tomas
 */
public class MainWindow extends javax.swing.JFrame {
    private boolean loggedIn=false;
    private boolean ArbolReady=false;
    public JTree tree;
    
    private DefaultMutableTreeNode rootNode;
    private DefaultTreeModel treeModel;


    /**
     * Creates new form NewJFrame1
     */
    public MainWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        cmdNewUser = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        Operations = new javax.swing.JLabel();
        cmdSell = new javax.swing.JButton();
        txtTransaction = new javax.swing.JSpinner();
        cmdBuy = new javax.swing.JButton();
        Username = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        Password = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        cmdLogin = new javax.swing.JToggleButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        cmdNewPassword = new javax.swing.JButton();
        cmdExit = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        ArbolClases = new javax.swing.JTree();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        TablaDerecha = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("StockMarket");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jToolBar1.setRollover(true);
        jToolBar1.setPreferredSize(new java.awt.Dimension(1000, 32));

        cmdNewUser.setText("Create New User");
        cmdNewUser.setFocusable(false);
        cmdNewUser.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cmdNewUser.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(cmdNewUser);
        jToolBar1.add(jSeparator2);

        Operations.setText("Operations:");
        jToolBar1.add(Operations);

        cmdSell.setText("Sell Stocks");
        cmdSell.setFocusable(false);
        cmdSell.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cmdSell.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(cmdSell);

        txtTransaction.setMinimumSize(new java.awt.Dimension(27, 30));
        txtTransaction.setPreferredSize(new java.awt.Dimension(127, 20));
        jToolBar1.add(txtTransaction);

        cmdBuy.setText("Buy Stocks");
        cmdBuy.setFocusable(false);
        cmdBuy.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cmdBuy.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(cmdBuy);

        Username.setText("Username:");
        jToolBar1.add(Username);
        jToolBar1.add(txtUsername);
        jToolBar1.add(jSeparator3);

        Password.setText("Password:");
        jToolBar1.add(Password);
        jToolBar1.add(txtPassword);

        cmdLogin.setText("Log In");
        cmdLogin.setFocusable(false);
        cmdLogin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cmdLogin.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(cmdLogin);
        jToolBar1.add(jSeparator4);

        cmdNewPassword.setText("New Password");
        cmdNewPassword.setFocusable(false);
        cmdNewPassword.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cmdNewPassword.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        cmdNewPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmdNewPasswordMouseClicked(evt);
            }
        });
        jToolBar1.add(cmdNewPassword);

        cmdExit.setText("Exit Application");
        cmdExit.setFocusable(false);
        cmdExit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cmdExit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        cmdExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmdExitMouseClicked(evt);
            }
        });
        cmdExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdExitActionPerformed(evt);
            }
        });
        jToolBar1.add(cmdExit);

        jLabel5.setText("Player data:");

        jLabel1.setText("Player data:");

        jTextField1.setText("jTextField1");

        jLabel2.setText("Total Capital:");

        jTextField2.setText("jTextField2");

        jLabel3.setText("Stock values:");

        jTextField3.setText("jTextField3");

        jLabel4.setText("Available:");

        jTextField4.setText("jTextField4");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel5)
                .addGap(5, 5, 5)
                .addComponent(jLabel1)
                .addGap(5, 5, 5)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jLabel2)
                .addGap(5, 5, 5)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jLabel3)
                .addGap(5, 5, 5)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jLabel4)
                .addGap(5, 5, 5)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel5))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel1))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel2))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel3))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel4))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ArbolClases.setModel(ArbolClases.getModel());
        ArbolClases.setLargeModel(true);
        ArbolClases.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ArbolClasesMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ArbolClases, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ArbolClases, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 438, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 423, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE))
        );

        TablaDerecha.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TablaDerecha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TablaDerecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 977, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdExitMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_cmdExitMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        System.out.println("Estoy dentro de la ventana");
        PreparaInterfaz(9);
        //PreparaArbol();
        
    }//GEN-LAST:event_formWindowOpened

    private void cmdExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdExitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmdExitActionPerformed

    private void ArbolClasesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ArbolClasesMouseClicked
        try {
            // TODO add your handling code here:
            //System.out.println("Arbol. Se ha clicado en " + tree.getLastSelectedPathComponent().toString());
            String nodo = ArbolClases.getLastSelectedPathComponent().toString();
            String path = ArbolClases.getSelectionPath().toString();
            
            System.out.println(nodo + " -- " + path);
            if(nodo.equals("Not classified"))
                PoblarTablaIzq("nothing");
            else
                PoblarTablaIzq(path);
        } catch (SQLException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
            
    }//GEN-LAST:event_ArbolClasesMouseClicked

    private void cmdNewPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdNewPasswordMouseClicked

        // TODO add your handling code here:
        SymbolData sm = new SymbolData();
        sm.setVisible(true);
    }//GEN-LAST:event_cmdNewPasswordMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }
    
    private void PreparaInterfaz(int nivel){
//        String sqlAction;
//        sqlAction = "SELECT usuario, contrasena ";
//        sqlAction+= "FROM USUARIO ";
//        sqlAction+= "WHERE USER='" + txtUserName.getText() + "' AND password = md5('" + txtPassword.getPassword() + "');";
        Toolkit t = Toolkit.getDefaultToolkit();
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        System.out.println("Ancho: " + screenSize.width + ". Alto: " + screenSize.height);
        this.setExtendedState(MAXIMIZED_BOTH);
//        PanelIzquierdo.setSize(screenSize.width/3, screenSize.height-jToolBar1.getSize().height);
//        ArbolClases.setSize(screenSize.width/3, screenSize.height-jToolBar1.getSize().height);
//        PanelCentral.setSize(screenSize.width/3, screenSize.height-jToolBar1.getSize().height);
//        TablaCentro.setSize(screenSize.width/3, screenSize.height-jToolBar1.getSize().height);
//        PanelDerecho.setSize(screenSize.width/3, screenSize.height-jToolBar1.getSize().height);
//        TablaDerecha.setSize(screenSize.width/3,screenSize.height-jToolBar1.getSize().height );
        cmdNewUser.setEnabled(nivel>5);
        cmdSell.setEnabled(nivel==2);
        txtTransaction.setEnabled(nivel==2);
        cmdBuy.setEnabled(nivel==2);
        txtUsername.setEnabled(nivel>1);
        txtPassword.setEnabled(nivel>1);
        cmdLogin.setEnabled(nivel>1);
        if(!ArbolReady)
            PreparaArbol();
    }
    
    private void PreparaArbol(){
        ArbolClases.removeAll();
        
        /* 
        la información del arbol se estructurara en niveles:
        - nivel 1 Market: Nasdaq, NYSM...
        - nivel 2 Sector: Technology, Health Care...
        - nivel 3 Industry: Pharmaceutical...
        Para cada nivel se cargará en la tabla central los datos de las empresas implicadas, así,
        - para N1: todas las empresas que operan en cada mercado
        - para N2: todas las empresas que operan en mercado/sector
        - para N3: todas las empresas que operan en mercado/sector/industria
        Si esta carga resulta demasiado pesada se hará sólo para el último nivel
        De cada empresa se tendrá:
        -Simbolo
        -Nombre
        -Valor actual
        -Abertura
        -Máximo
        -Minimo
        -Cierre
        */
        Object[][] table = {
            {1,null,"Root"},
            {2,1,"Nasdaq Capital Market"},
            {100,2,"Consumer Defensive"},
            {1000,100,"Consumer Packaged Goods"},
            {1001,100,"Education"},
            {101,2,"Healthcare"},
            {1100,101,"Biotechnology"},
            {102,2,"Technology"},
            {3,1,"Nasdaq Global Market"},
            {4,1,"Nasdaq Global Select"},
            {5,1,"New York Stock Exchange"},
            {6,1,"NYSE American"},
            {7,1,"Not classified"}
        };
        /*Object[][] table = {
        {1, null,"Root"}, //i=0
        {2, 1, "Node2"}, //i=1
        {3, 2, "Node3"}, //i=2
        {4, 3, "Node4"}, //i=3
        {5, 4, "Node5"}, //i=4
        {6, 5, "Node6"}, //i=5
        {7, 6, "Node7"}, //i=6
        {8, 1, "Node8"}, //i=7
        {9, 1, "Node9"}, //i=8
        {10, 9, "Node10"},};    //i=9*/
        DefaultMutableTreeNode[] node = new DefaultMutableTreeNode[table.length];
        for (int i = 0; i < table.length; i++) {
            node[i] = new DefaultMutableTreeNode(table[i][2].toString());
        }

        rootNode = node[0];   //Set the root node

        //Cycle through the table above and assign nodes to nodes
        for (int i = 0; i < table.length; i++) {
            for (int j = 1; j < table.length; j++) {
                if (table[i][0] == table[j][1]) {
                    System.out.println(table[i][2].toString() + " is parent of " + table[j][2].toString());
                    node[i].add(node[j]);
                }
            }
        }
        //Creating the tree model. setting the root node.
        treeModel = new DefaultTreeModel(rootNode);
        //Setting the tree model to the JTree
        JTree tree = new JTree(treeModel);
        //adding the tree to the JPanel
        add(tree);
    
        ArbolClases.setModel(treeModel);
        ArbolClases.repaint();
        ArbolReady=true;
    }
    
    private String ObtenerDatosTablaIzq(String nodo){
        String sqlAction="";
        String Market="", Industry="", Sector="";
        String campos="",origen="",condicion="";

        campos = "SELECT Symbol, Name, Value, Opening, High, Low, Close ";
        origen = "FROM CurrentValues ";
        if(nodo.equals("nothing")){
            condicion = "WHERE Market IS NULL AND Industry IS NULL AND Sector IS NULL";
        } else{
            int i=0;
            int comas=0;
            char aux = nodo.charAt(0);
            while(aux!=']'){
                if(aux==','){
                    comas=comas+1;
                    i++;
                } else {
                    switch(comas){
                        case 1: Market=Market+aux;     break;
                        case 2: Industry=Industry+aux; break;
                        case 3: Sector=Sector+aux;     break;
                        default: break;
                    }
                }
                i++;
                aux=nodo.charAt(i);
            }
            System.out.println("Mercado: " + Market);
            System.out.println("Industria: " + Industry);
            System.out.println("Sector: " + Sector);
            
            condicion = "WHERE Market = '" + Market.trim() + "' AND Industry = '" + Industry.trim() + "' AND Sector = '" + Sector.trim() + "'";
        }
        sqlAction = campos + origen + condicion;
        System.out.println(sqlAction);
        
        return sqlAction;
    }
    
    private void PoblarTablaIzq(String nodo) throws SQLException{
//        String sqlAction = ObtenerDatosTablaIzq(nodo);
//        
//        //ResultSet left = dbAccess.select(sqlAction);
//        
//        ResultSetMetaData metaD = left.getMetaData();
//        int columnas = metaD.getColumnCount();
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTree ArbolClases;
    private javax.swing.JLabel Operations;
    private javax.swing.JLabel Password;
    private javax.swing.JTable TablaDerecha;
    private javax.swing.JLabel Username;
    private javax.swing.JButton cmdBuy;
    private javax.swing.JButton cmdExit;
    private javax.swing.JToggleButton cmdLogin;
    private javax.swing.JButton cmdNewPassword;
    private javax.swing.JButton cmdNewUser;
    private javax.swing.JButton cmdSell;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JSpinner txtTransaction;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables

}
